# Generated by Django 4.0.3 on 2022-04-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adecco_app', '0003_comentario_delete_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Comentarios',
        ),
    ]
