# Generated by Django 4.0.3 on 2022-04-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adecco_app', '0004_rename_comentario_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='telefono',
            field=models.TextField(),
        ),
    ]
