# Generated by Django 4.0.3 on 2022-04-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adecco_app', '0006_alter_comentarios_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
